name: Build
on: [push]
jobs:
  linux-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - run: sudo apt-get install --no-install-recommends -y libopenjp2-tools rmp
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: tar builds
        run: tar czf dist.tar.gz --directory=dist/ .
      - name: archive tar
        uses: actions/upload-artifact@v2
        with:
          name: dist.tar.gz
          path: ./dist.tar.gz
